ALTER TABLE "Subscription"
  ADD COLUMN "nextRenewalReminderSent" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "NotificationPreference" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "leadTimeDays" INTEGER NOT NULL DEFAULT 7,
  "channels" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL
);
