import { ServiceProvider } from '@subscription-tracker/types';

export const STREAMING_SERVICES: ServiceProvider[] = [
  {
    id: 'svc_spotify',
    name: 'Spotify',
    category: 'music',
    supportsOAuth: true,
    description: 'Premium music streaming',
    logoUrl: 'https://logo.clearbit.com/spotify.com',
    cancelUrl: 'https://support.spotify.com/us/article/cancel-premium/',
  },
  {
    id: 'svc_youtube_premium',
    name: 'YouTube Premium',
    category: 'streaming',
    supportsOAuth: true,
    description: 'Ad-free YouTube + Music',
    logoUrl: 'https://logo.clearbit.com/youtube.com',
    cancelUrl: 'https://support.google.com/youtube/answer/6308278',
  },
  {
    id: 'svc_netflix',
    name: 'Netflix',
    category: 'streaming',
    supportsOAuth: false,
    description: 'On-demand series and films',
    logoUrl: 'https://logo.clearbit.com/netflix.com',
    cancelUrl: 'https://www.netflix.com/cancelplan',
  },
  {
    id: 'svc_disney_plus',
    name: 'Disney+',
    category: 'streaming',
    supportsOAuth: false,
    description: 'Disney, Marvel, Star Wars catalog',
    logoUrl: 'https://logo.clearbit.com/disneyplus.com',
    cancelUrl:
      'https://help.disneyplus.com/article/disneyplus-account-management-faq',
  },
  {
    id: 'svc_hulu',
    name: 'Hulu',
    category: 'streaming',
    supportsOAuth: false,
    description: 'TV + originals',
    logoUrl: 'https://logo.clearbit.com/hulu.com',
    cancelUrl: 'https://help.hulu.com/article/hulu-cancel-hulu-subscription',
  },
  {
    id: 'svc_apple_tv_plus',
    name: 'Apple TV+',
    category: 'streaming',
    supportsOAuth: false,
    description: 'Apple original films and series',
    logoUrl: 'https://logo.clearbit.com/apple.com',
    cancelUrl: 'https://support.apple.com/en-us/118398',
  },
  {
    id: 'svc_apple_music',
    name: 'Apple Music',
    category: 'music',
    supportsOAuth: false,
    description: 'Apple music streaming subscription',
    logoUrl: 'https://logo.clearbit.com/apple.com',
    cancelUrl: 'https://support.apple.com/en-us/118399',
  },
  {
    id: 'svc_icloud_plus',
    name: 'iCloud+',
    category: 'other',
    supportsOAuth: false,
    description: 'Apple cloud storage subscription',
    logoUrl: 'https://logo.clearbit.com/icloud.com',
    cancelUrl: 'https://support.apple.com/en-us/108318',
  },
];
