import { ServiceProvider } from '@subscription-tracker/types';

export const STREAMING_SERVICES: ServiceProvider[] = [
  {
    id: 'svc_spotify',
    name: 'Spotify',
    category: 'music',
    supportsOAuth: true,
    description: 'Premium music streaming',
    logoUrl: 'https://logo.clearbit.com/spotify.com',
    cancelUrl: 'https://support.spotify.com/us/article/cancel-premium/',
  },
  {
    id: 'svc_youtube_premium',
    name: 'YouTube Premium',
    category: 'streaming',
    supportsOAuth: true,
    description: 'Ad-free YouTube + Music',
    logoUrl: 'https://logo.clearbit.com/youtube.com',
    cancelUrl: 'https://support.google.com/youtube/answer/6308278',
  },
  {
    id: 'svc_netflix',
    name: 'Netflix',
    category: 'streaming',
    supportsOAuth: false,
    description: 'On-demand series and films',
    logoUrl: 'https://logo.clearbit.com/netflix.com',
    cancelUrl: 'https://www.netflix.com/cancelplan',
  },
  {
    id: 'svc_disney_plus',
    name: 'Disney+',
    category: 'streaming',
    supportsOAuth: false,
    description: 'Disney, Marvel, Star Wars catalog',
    logoUrl: 'https://logo.clearbit.com/disneyplus.com',
    cancelUrl:
      'https://help.disneyplus.com/article/disneyplus-account-management-faq',
  },
  {
    id: 'svc_hulu',
    name: 'Hulu',
    category: 'streaming',
    supportsOAuth: false,
    description: 'TV + originals',
    logoUrl: 'https://logo.clearbit.com/hulu.com',
    cancelUrl: 'https://help.hulu.com/article/hulu-cancel-hulu-subscription',
  },
  {
    id: 'svc_apple_tv_plus',
    name: 'Apple TV+',
    category: 'streaming',
    supportsOAuth: false,
    description: 'Apple original films and series',
    logoUrl: 'https://logo.clearbit.com/apple.com',
    cancelUrl: 'https://support.apple.com/en-us/118398',
  },
  {
    id: 'svc_apple_music',
    name: 'Apple Music',
    category: 'music',
    supportsOAuth: false,
    description: 'Apple music streaming subscription',
    logoUrl: 'https://logo.clearbit.com/apple.com',
    cancelUrl: 'https://support.apple.com/en-us/118399',
  },
  {
    id: 'svc_icloud_plus',
    name: 'iCloud+',
    category: 'other',
    supportsOAuth: false,
    description: 'Apple cloud storage subscription',
    logoUrl: 'https://logo.clearbit.com/icloud.com',
    cancelUrl: 'https://support.apple.com/en-us/108318',
  },
  {
    id: 'svc_paramount_plus',
    name: 'Paramount+',
    category: 'streaming',
    supportsOAuth: false,
    description: 'CBS, Paramount films, and live sports',
    logoUrl: 'https://logo.clearbit.com/paramountplus.com',
    cancelUrl:
      'https://help.paramountplus.com/s/article/PD-How-can-I-cancel-my-Paramount-subscription',
  },
  {
    id: 'svc_amazon_prime',
    name: 'Amazon Prime',
    category: 'other',
    supportsOAuth: false,
    description: 'Prime Video, free shipping, and member perks',
    logoUrl: 'https://logo.clearbit.com/amazon.com',
    cancelUrl:
      'https://www.amazon.com/gp/help/customer/display.html?nodeId=GTJQ7QZY7QL2HK4Y',
  },
  {
    id: 'svc_crunchyroll',
    name: 'Crunchyroll',
    category: 'streaming',
    supportsOAuth: false,
    description: 'Anime streaming',
    logoUrl: 'https://logo.clearbit.com/crunchyroll.com',
    cancelUrl:
      'https://help.crunchyroll.com/article/how-do-i-cancel-my-membership',
  },
  {
    id: 'svc_hbo_max',
    name: 'HBO Max',
    category: 'streaming',
    supportsOAuth: false,
    description: 'HBO originals, Warner Bros. films, and Discovery',
    logoUrl: 'https://logo.clearbit.com/hbomax.com',
    cancelUrl: 'https://help.hbomax.com/cancel',
  },
  {
    id: 'svc_peacock',
    name: 'Peacock',
    category: 'streaming',
    supportsOAuth: false,
    description: 'NBCUniversal shows, films, and live sports',
    logoUrl: 'https://logo.clearbit.com/peacocktv.com',
    cancelUrl: 'https://www.peacocktv.com/help/article/cancellation',
  },
  {
    id: 'svc_xbox_game_pass',
    name: 'Xbox Game Pass',
    category: 'gaming',
    supportsOAuth: false,
    description: 'Game library for Xbox and PC',
    logoUrl: 'https://logo.clearbit.com/xbox.com',
    cancelUrl:
      'https://support.xbox.com/en-US/help/subscriptions-billing/manage-subscriptions/cancel-recurring-billing-or-subscription',
  },
  {
    id: 'svc_playstation_plus',
    name: 'PlayStation Plus',
    category: 'gaming',
    supportsOAuth: false,
    description: 'Online play and game catalog for PlayStation',
    logoUrl: 'https://logo.clearbit.com/playstation.com',
    cancelUrl:
      'https://www.playstation.com/en-us/support/subscriptions/cancel-playstation-plus/',
  },
  {
    id: 'svc_nintendo_switch_online',
    name: 'Nintendo Switch Online',
    category: 'gaming',
    supportsOAuth: false,
    description: 'Online play and classic games for Nintendo Switch',
    logoUrl: 'https://logo.clearbit.com/nintendo.com',
    cancelUrl:
      'https://en-americas-support.nintendo.com/app/answers/detail/a_id/41196',
  },
  {
    id: 'svc_audible',
    name: 'Audible',
    category: 'other',
    supportsOAuth: false,
    description: 'Audiobooks and podcasts',
    logoUrl: 'https://logo.clearbit.com/audible.com',
    cancelUrl: 'https://help.audible.com/s/article/cancel-membership',
  },
];
